# Generated by Django 4.2.30 on 2026-05-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Business Owner'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=15),
        ),
    ]
